### ISSUE TITLE
Show markings on submit

### ISSUE THREAD

**Issue by barryjenkin** [cgkineo/adapt-submitAll#1]
Hi there. I've got this working pretty well, although can't seem to get markings to show on clicking Submit (as shown in the demo). I've switched markings on in my Assessment extension. Any ideas?
The markings do appear when I leave the page and come back, but not on the same page after submission.

**Comment by moloko** [comment]
Curious, it seems fine in the test package I set up when prepping this extension to add to github. There's a copy of the build of that [here](https://github.com/cgkineo/adapt-submitAll/files/726399/submitAll-test.zip), see the assessment page...

**Comment by barryjenkin** [comment]
could you let me know what assessment settings you have switched on/off? wonder if something's overriding the show markings setting.

**Comment by moloko** [comment]
as far as I recall, all I changed was:
![2017-01-24 12_41_04-articles json - src - visual studio code](https://cloud.githubusercontent.com/assets/1249597/22247582/731d0edc-e232-11e6-9847-0c3a6a6a94c9.png)

**Comment by moloko** [comment]
FYI it's framework 2.0.15 (probably with some of 2.0.16 in there too) with assessment 2.0.8

**Comment by barryjenkin** [comment]
Thanks! I aligned all my settings but still no luck.. I was using 2.0.1. The example in submitAll-test is exactly what I'm trying to achieve. Is the split setting important? I've been leaving this blank.

**Comment by moloko** [comment]
No, the split setting has no relevance to this.

If you are using assessment v2.0.1 it's probably because of that - that's nearly 15 months out of date...

**Comment by barryjenkin** [comment]
Sorry i meant the submitAll extension was 2.0.1. Assessment is 2.0.8. I tried another from scratch using the generic theme and still couldn't get it to work. Are you able to share your settings in one of the actual quiz components?

Here's how it looks in Chrome post-submit:

![screen shot 2017-01-26 at 11 58 51 am](https://cloud.githubusercontent.com/assets/24560844/22316108/f647b482-e3be-11e6-812b-bc6e1ff12787.png)

**Comment by tomgreenfield** [comment]
I'd check that you haven't accidently allowed multiple attempts on each question.

**Comment by moloko** [comment]
Unless the article you've applied submitAll to has a block/blocks containing only presentation components then you don't want to be using trickle within that article.
> Are you able to share your settings in one of the actual quiz components?

there's a copy of my test build attached to my original reply

**Comment by barryjenkin** [comment]
Yep no trickle anywhere or multiple attempts on the questions. Might just reinstall and see how I go.
