### ISSUE TITLE
Unfortanetely it doesn't seem to work with the newest build

### ISSUE THREAD

**Issue by mike-st** [cgkineo/adapt-submitAll#3]
Unfortunately it doesn't seem to work with the newest build.  

Adapt authoring tool v0.3.0
Adapt Framework v2.2.1

**Comment by moloko** [comment]
Hi @mike-st I've just tried it on a v2.2.1 course (in the framework) and it worked absolutely fine...

Could you give more details about what's not working for you?

**Comment by mike-st** [comment]
Hi I should have clarified it works with the framework but not in the authoring tool. I can see the options under extensions when I view the article properties but when I set the submit button to true and preview the course in the authoring tool. It displays all the multiple choice questions submit buttons as it normally does and doesn't hide them all but the last one. I have tried this on two computers running the authoring tool and got the same results.

**Comment by moloko** [comment]
Are you able to attach a sample build for me to have a look at? Just the build will do - but build and src would be preferable if you can

**Comment by mike-st** [comment]
My apologies after further research. I found out my instance wasn't saving the extension to the  "temp" folder therefore breaking it from working properly. Once I added it to the "temp/extension" folder manually it worked perfectly. Thanks though for the help
