### ISSUE TITLE
Button inactive when using Text Inputs

### ISSUE THREAD

**Issue by barryjenkin** [cgkineo/adapt-submitAll#4]
When using submitAll in an article with Text Input components, the button stays inactive after completing the quiz (i.e. entering text in the last text-input cell wherever that may be in the order). To get the button to activate I'm finding I have to either click inside another cell or scroll away and back again. Ideally I guess I'm looking for it to activate soon as a key is entered in the last remaining question. Should this be happening and is there a way round this? I'm using the latest 0.4.0 tool with updated plugins and testing in the Vanilla theme.

**Comment by moloko** [comment]
hi @barryjenkin we've never used this extension with textInput components before so it doesn't surprise me that it doesn't work.

If you look at [this line of code](https://github.com/cgkineo/adapt-submitAll/blob/master/js/adapt-submitAll.js#L80) you'll see it's either a `click` or `inview` event that triggers the extension to check if all the questions are ready for submission or not, so it's not really set up for detecting when the user has answered a textInput sufficiently.

Needs a bit of thinking as what event should be added in there...
