### ISSUE TITLE
needs updating for FW v5 compatibility

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-submitAll#5]

**Comment by barryjenkin** [comment]
Hey Matt. Is fw2 still the highest this is compatible with? Been hanging to bump all my courses up to fw5.

**Comment by moloko** [comment]
Hey @barryjenkin have a look at PR #9 - you may find it's close enough for you to be able to finish.

I know we're planning to use this on an internal project fairly soon - if that goes ahead this will definitely get finished off properly.
